spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none # 경고 절대 다른 것으로 수정하지 마세요!!
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  profiles:
    default: prod

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      org.hibernate.SQLQuery: debug

#mail:
#  address:
#    admin: admin@gmail.com
